[toolchain]
anchor_version = "0.30.1"  
solana_version = "1.18.17" 

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_sbt = "8nQ4PwDCH3uWrdjZ7YPVGKhkbbmfh4QAFgfvJzmJBJSK"

# Add this section
[programs.devnet]
solana_sbt = "8nQ4PwDCH3uWrdjZ7YPVGKhkbbmfh4QAFgfvJzmJBJSK"

[programs.mainnet]
solana_sbt = "8nQ4PwDCH3uWrdjZ7YPVGKhkbbmfh4QAFgfvJzmJBJSK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Set source RPC for clone
[test.validator]
url = "https://api.devnet.solana.com"
[test]
startup_wait = 100000

## Clone Metaplex program from Devnet
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
